//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.ComicsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComicsReference.IComics")]
    public interface IComics {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/GetComics", ReplyAction="http://tempuri.org/IComics/GetComicsResponse")]
        ApplicationService.DTOs.ComicsDTO[] GetComics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/GetComics", ReplyAction="http://tempuri.org/IComics/GetComicsResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ComicsDTO[]> GetComicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/PostComics", ReplyAction="http://tempuri.org/IComics/PostComicsResponse")]
        string PostComics(ApplicationService.DTOs.ComicsDTO comicsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/PostComics", ReplyAction="http://tempuri.org/IComics/PostComicsResponse")]
        System.Threading.Tasks.Task<string> PostComicsAsync(ApplicationService.DTOs.ComicsDTO comicsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/PutComics", ReplyAction="http://tempuri.org/IComics/PutComicsResponse")]
        string PutComics(ApplicationService.DTOs.ComicsDTO comicsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/PutComics", ReplyAction="http://tempuri.org/IComics/PutComicsResponse")]
        System.Threading.Tasks.Task<string> PutComicsAsync(ApplicationService.DTOs.ComicsDTO comicsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/DeleteComics", ReplyAction="http://tempuri.org/IComics/DeleteComicsResponse")]
        string DeleteComics(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/DeleteComics", ReplyAction="http://tempuri.org/IComics/DeleteComicsResponse")]
        System.Threading.Tasks.Task<string> DeleteComicsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/Message", ReplyAction="http://tempuri.org/IComics/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComics/Message", ReplyAction="http://tempuri.org/IComics/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComicsChannel : Website.ComicsReference.IComics, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComicsClient : System.ServiceModel.ClientBase<Website.ComicsReference.IComics>, Website.ComicsReference.IComics {
        
        public ComicsClient() {
        }
        
        public ComicsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComicsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComicsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComicsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.ComicsDTO[] GetComics() {
            return base.Channel.GetComics();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ComicsDTO[]> GetComicsAsync() {
            return base.Channel.GetComicsAsync();
        }
        
        public string PostComics(ApplicationService.DTOs.ComicsDTO comicsDto) {
            return base.Channel.PostComics(comicsDto);
        }
        
        public System.Threading.Tasks.Task<string> PostComicsAsync(ApplicationService.DTOs.ComicsDTO comicsDto) {
            return base.Channel.PostComicsAsync(comicsDto);
        }
        
        public string PutComics(ApplicationService.DTOs.ComicsDTO comicsDto) {
            return base.Channel.PutComics(comicsDto);
        }
        
        public System.Threading.Tasks.Task<string> PutComicsAsync(ApplicationService.DTOs.ComicsDTO comicsDto) {
            return base.Channel.PutComicsAsync(comicsDto);
        }
        
        public string DeleteComics(int id) {
            return base.Channel.DeleteComics(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteComicsAsync(int id) {
            return base.Channel.DeleteComicsAsync(id);
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
    }
}
