//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.SeriesReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeriesReference.ISeries")]
    public interface ISeries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/GetSeries", ReplyAction="http://tempuri.org/ISeries/GetSeriesResponse")]
        ApplicationService.DTOs.SeriesDTO[] GetSeries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/GetSeries", ReplyAction="http://tempuri.org/ISeries/GetSeriesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.SeriesDTO[]> GetSeriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/PostSeries", ReplyAction="http://tempuri.org/ISeries/PostSeriesResponse")]
        string PostSeries(ApplicationService.DTOs.SeriesDTO seriesDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/PostSeries", ReplyAction="http://tempuri.org/ISeries/PostSeriesResponse")]
        System.Threading.Tasks.Task<string> PostSeriesAsync(ApplicationService.DTOs.SeriesDTO seriesDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/PutSeries", ReplyAction="http://tempuri.org/ISeries/PutSeriesResponse")]
        string PutSeries(ApplicationService.DTOs.SeriesDTO seriesDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/PutSeries", ReplyAction="http://tempuri.org/ISeries/PutSeriesResponse")]
        System.Threading.Tasks.Task<string> PutSeriesAsync(ApplicationService.DTOs.SeriesDTO seriesDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/DeleteSeries", ReplyAction="http://tempuri.org/ISeries/DeleteSeriesResponse")]
        string DeleteSeries(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/DeleteSeries", ReplyAction="http://tempuri.org/ISeries/DeleteSeriesResponse")]
        System.Threading.Tasks.Task<string> DeleteSeriesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/Message", ReplyAction="http://tempuri.org/ISeries/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeries/Message", ReplyAction="http://tempuri.org/ISeries/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeriesChannel : Website.SeriesReference.ISeries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeriesClient : System.ServiceModel.ClientBase<Website.SeriesReference.ISeries>, Website.SeriesReference.ISeries {
        
        public SeriesClient() {
        }
        
        public SeriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.SeriesDTO[] GetSeries() {
            return base.Channel.GetSeries();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.SeriesDTO[]> GetSeriesAsync() {
            return base.Channel.GetSeriesAsync();
        }
        
        public string PostSeries(ApplicationService.DTOs.SeriesDTO seriesDto) {
            return base.Channel.PostSeries(seriesDto);
        }
        
        public System.Threading.Tasks.Task<string> PostSeriesAsync(ApplicationService.DTOs.SeriesDTO seriesDto) {
            return base.Channel.PostSeriesAsync(seriesDto);
        }
        
        public string PutSeries(ApplicationService.DTOs.SeriesDTO seriesDto) {
            return base.Channel.PutSeries(seriesDto);
        }
        
        public System.Threading.Tasks.Task<string> PutSeriesAsync(ApplicationService.DTOs.SeriesDTO seriesDto) {
            return base.Channel.PutSeriesAsync(seriesDto);
        }
        
        public string DeleteSeries(int id) {
            return base.Channel.DeleteSeries(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSeriesAsync(int id) {
            return base.Channel.DeleteSeriesAsync(id);
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
    }
}
